# This file was autogenerated by uv via the following command:
#    uv pip compile ./config/requirements/base.in --output-file ./config/requirements/base_py3-8.txt --universal --python 3.8
anyio==4.5.2
    # via httpx
asgiref==3.8.1
    # via django
attrs==24.2.0
    # via
    #   outcome
    #   trio
backports-zoneinfo==0.2.1 ; python_full_version < '3.9'
    # via django
certifi==2024.8.30
    # via
    #   httpcore
    #   httpx
cffi==1.17.1 ; implementation_name != 'pypy' and os_name == 'nt'
    # via trio
django==4.2.16
    # via -r ./config/requirements/base.in
exceptiongroup==1.2.2 ; python_full_version < '3.11'
    # via
    #   anyio
    #   trio
h11==0.14.0
    # via httpcore
httpcore==1.0.7
    # via httpx
httpx==0.28.0
    # via -r ./config/requirements/base.in
idna==3.10
    # via
    #   anyio
    #   httpx
    #   trio
outcome==1.3.0.post0
    # via trio
pip==24.3.1
    # via -r ./config/requirements/base.in
pycparser==2.22 ; implementation_name != 'pypy' and os_name == 'nt'
    # via cffi
python-dotenv==1.0.1
    # via -r ./config/requirements/base.in
sniffio==1.3.1
    # via
    #   anyio
    #   trio
sortedcontainers==2.4.0
    # via trio
sqlparse==0.5.2
    # via django
trio==0.26.2
    # via -r ./config/requirements/base.in
typing-extensions==4.12.2 ; python_full_version < '3.11'
    # via
    #   anyio
    #   asgiref
tzdata==2024.2 ; sys_platform == 'win32'
    # via django
urllib3==1.26.20
    # via -r ./config/requirements/base.in
uv==0.5.5
    # via -r ./config/requirements/base.in
